import java
from typing import Any

Material = java.type("org.bukkit.Material")
BukkitItemStack = java.type("org.bukkit.inventory.ItemStack")
Bukkit = java.type("org.bukkit.Bukkit")
Inventory = java.type("org.bukkit.inventory.Inventory")
NamespacedKey = java.type("org.bukkit.NamespacedKey")
RegistryAccess = java.type("io.papermc.paper.registry.RegistryAccess")
RegistryKey = java.type("io.papermc.paper.registry.RegistryKey")
AdventureComponent:Any = java.type("net.kyori.adventure.text.Component")
AdventureTextColor:Any = java.type("net.kyori.adventure.text.format.TextColor")
AdventureTextDecoration:Any = java.type("net.kyori.adventure.text.format.TextDecoration")
DecorationState = java.type("net.kyori.adventure.text.format.TextDecoration$State")
NamedTextColor:Any=java.type("net.kyori.adventure.text.format.NamedTextColor")
TextComponentImpl = java.type("net.kyori.adventure.text.TextComponent")
AdventureKey:Any=java.type("net.kyori.adventure.key.Key")
ArrayList:Any=java.type("java.util.ArrayList")
PlainTextSerializer = java.type("net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer")
AdventureClickEvent: Any = java.type("net.kyori.adventure.text.event.ClickEvent")
AdventureClickAction: Any = java.type("net.kyori.adventure.text.event.ClickEvent$Action")
AdventureHoverEvent: Any = java.type("net.kyori.adventure.text.event.HoverEvent")
JavaUUID: Any = java.type("java.util.UUID")
EntityType:Any=java.type("org.bukkit.entity.EntityType")